name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust nightly
      run: |
        rustup toolchain install nightly
        rustup component add --toolchain nightly rustfmt
    - name: Check formatting
      run: cd src-tauri; cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install libgtk-3-dev
    - name: Set up Rust nightly
      run: |
        rustup toolchain install nightly
        rustup component add --toolchain nightly clippy
    - name: Run clippy
      run: cd src-tauri; cargo clippy
